#!/bin/dash
# Created by Nikil Singh z5209322

# First check if there are one or more arguements on command line not including
# this actual shell.
if test $# -ne 0
then
    echo "usage: legit-init"
    exit 1
fi

if test -d .legit
then
    echo "legit-init: error: .legit already exists"
else
    mkdir .legit                            # Initialises the .legit folder.
    mkdir .legit/.index                     # Holds all current files and branches added.
    mkdir .legit/.index/master              # Holds all the master branch.
    mkdir .legit/.prev                      # Holds all files based on commit number.
    mkdir .legit/.prev/master               # Holds all versions of master.
    touch .legit/.prev/commitLog.txt        # Generates text file to log commits.
    touch .legit/branch.txt                 # Generates text file to hold current branch name.
    echo  "master" > .legit/branch.txt      # Enters current branch into file.

    echo "Initialized empty legit repository in .legit"
fi
