#!/bin/dash
# Created by Nikil Singh z5209322

# Check if a .legit directory has been initialised.
if  ! test -d .legit
then
    echo "legit-add: error: no .legit directory containing legit repository exists"
    exit 1
fi

# Check if there are arguements.
if test $# -eq 0
then
    echo "legit-add: error: internal error Nothing specified, nothing added."
    exit 1
fi

# Check if all arguements are valid files.
for file in $@
do
    # If file exists in index but not current directory.
    if test -e .legit/.index/master/$file
    then
        if ! test -e $file
        then
            # Since it is no longer in the current directory.
            rm .legit/.index/master/$file
        fi
    elif ! test -e $file
    then
        echo "legit-add: error: can not open '$file'"
        exit 1
    fi
done

# Adds the files to the index.
for file in $@
do
    # Checks if file exists to account for file that got deleted.
    if test -e $file
    then
        cp $file ".legit/.index/master"
    fi
done
