#!/bin/dash
# Created by Nikil Singh z5209322

# Check if a .legit directory has been initialised.
if  ! test -d .legit
then
    echo "legit-add: error: no .legit directory containing legit repository exists"
    exit 1
fi

# Gets the current branch.
branch=`cat .legit/branch.txt`

# Checks if a temporary index is being used when switching branches.
if test -d ".legit/.tmpInd"
then
    # If temporary branch exists, set index to tempInd.
    index=".tmpInd"
else
    # If temporary branch does not exist, set index to that of the current
    # branches.
    index=".index/$branch"
fi

# Check if there are arguements.
if test $# -eq 0
then
    echo "legit-add: error: internal error Nothing specified, nothing added."
    exit 1
fi

# Check if all arguements are valid files.
for file in $@
do
    # Checks if file exists in index.
    if test -e .legit/$index/$file
    then
        # Checks if file does not exist in current directory.
        if ! test -e $file
        then
            # Since it is no longer in the current directory.
            rm .legit/$index/$file
        fi
    # Checks if file does not exist in index nor current directory.
    elif ! test -e $file
    then
        echo "legit-add: error: can not open '$file'"
        exit 1
    fi
done

# Adds the files to the index.
for file in $@
do
    # Checks if file exists to account for if file that got deleted.
    if test -e $file
    then
        # Copies file from current directory into index.
        cp $file ".legit/$index"
    fi
done
