#!/bin/dash
# Created by Nikil Singh z5209322

# Check if a .legit directory has been initialised.
if  ! test -d .legit
then
    echo "legit-log: error: no .legit directory containing legit repository exists"
    exit 1
fi

# Gets the current branch.
branch=`cat .legit/branch.txt`

# Checks if commit log is empty.
if ! test -s .legit/.commits/commitLog.txt
then
    echo "legit-log: error: your repository does not have any commits yet"
    exit 1
fi

# Checks if any arguements were given.
if test $# -ne 0
then
    echo "usage: legit-log"
    exit 1
fi

# Prints out the commit log for that branch.
file=".legit/.prev/$branch/branchLog.txt"
tac $file
