#!/bin/dash
# Created by Nikil Singh z5209322

# Check if a .legit directory has been initialised.
if  ! test -d .legit
then
    echo "legit-add: error: no .legit directory containing legit repository exists"
    exit 1
fi

# Checks if repository has any commits.
# Gets number of previous commits.
numCommits=`ls -l .legit/.prev/master/| egrep -c ^d`
if ! ls -l .legit/.prev/master/| egrep -c ^d > /dev/null
then
    echo "legit-rm: error: your repository does not have any commits yet"
    exit 1
fi

files=""    # Variable to hold all files.
found=0     # Variable for whether a file has been seen.
# Gets all the files from current directory, index and the previous commit.
# Checks all files in current directory.
numFiles=`ls -l | egrep -c ^-`
if test $numFiles -ne 0
then
    for file in *
    do
        # Checks if file is not a directory.
        if ! test -d $file
        then
            found=0
            # Checks if file is already held in $files.
            for tmpFile in $files
            do
                # Checks for duplicate files.
                if test $tmpFile = $file
                then
                    found=1
                fi
            done
            # If the file is not a duplicate file.
            if test $found -eq 0
            then
                # Concatenates the filename to $files separated by a space.
                files=`echo $files $file`
            fi
        fi
    done
fi

found=0
# Checks all files in index
numFiles=`ls -l .legit/.index/master| egrep -c ^-`
if test $numFiles -ne 0
then
    for file in .legit/.index/master/*
    do
        # Checks if file is not a directory.
        modifiedFile=`echo $file | sed 's/.*[/]//g'`
        if ! test -d $file
        then
            found=0
            # Checks if file is already held in $files.
            for tmpFile in $files
            do
                # Checks for duplicate files.
                if test $tmpFile = $modifiedFile
                then
                    found=1
                fi
            done
            # If the file is not a duplicate file.
            if test $found -eq 0
            then
                files=`echo $files $modifiedFile`
            fi
        fi
    done
fi

found=0
# Gets number of previous commits.
numCommits=`ls -l .legit/.prev/master/| egrep -c ^d`
# Sets previous commit number to be one less than total commits as they start
# from 0.
prevCommit=`expr $numCommits - 1`
# Checks all files in previous commit.
numFiles=`ls -l .legit/.prev/master/$prevCommit| egrep -c ^-`
if test $numFiles -ne 0
then
    for file in .legit/.prev/master/$prevCommit/*
    do
        # Checks if file is not a directory.
        modifiedFile=`echo $file | sed 's/.*[/]//g'`
        if ! test -d $file
        then
            found=0
            # Checks if file is already held in $files.
            for tmpFile in $files
            do
                # Checks for duplicate files.
                if test $tmpFile = $modifiedFile
                then
                    found=1
                fi
            done
            # If the file is not a duplicate file.
            if test $found -eq 0
            then
                files=`echo $files $modifiedFile`
            fi
        fi
    done
fi
# Sorts all the files into alphabetical order.
# Creates a tmpFile to hold alphabetically sorted files.
touch .legit/tmpFile

for file in $files
do
    # Outputs each file into the tmpFile
    echo $file >> .legit/tmpFile
done

# Sorts the file in tmpFile.
files=`sort .legit/tmpFile`

# Removes the tmp file.
rm .legit/tmpFile

# Compare the files in current directory, index and previous commit, then outputs
# the appropriate message for that file describing its status.
for file in $files
do
    # If file is in current directory, index and previous commit.
    if test -e $file -a -e .legit/.index/master/$file -a -e .legit/.prev/master/$prevCommit/$file
    then
        # Checks if file in index is NOT the same as file in current directory.
        if ! diff .legit/.index/master/$file $file > /dev/null
        then
            # Checks if file in index is NOT the same as file in previous commit.
            if ! diff .legit/.index/master/$file .legit/.prev/master/$prevCommit/$file > /dev/null
            then
                # Here file in Index != Current Directory [== || !=] Previous Commit.
                echo "$file - file changed, different changes staged for commit"
            else
                # Here file in Current Directory != Index == Previous Commit.
                echo "$file - file changed, changes not staged for commit"
            fi
        else
            # Checks if file in index is NOT the same as file in previous commit.
            if ! diff .legit/.index/master/$file .legit/.prev/master/$prevCommit/$file > /dev/null
            then
                # Here file in Index == Current Directory != Previous Commit.
                echo "$file - file changed, changes staged for commit"
            else
                # Here file in Index == Current Directory == Previous Commit.
                echo "$file - same as repo"
            fi
        fi

    # If file is in current directory and index.
    elif test -e $file -a -e .legit/.index/master/$file
    then
        echo "$file - added to index"

    # If file is in index and previous commit.
    elif test -e .legit/.index/master/$file -a -e .legit/.prev/master/$prevCommit/$file
    then
        # Checks if file in index is NOT the same as file in previous commit.
        if ! diff .legit/.index/master/$file .legit/.prev/master/$prevCommit/$file > /dev/null
        then
            # Here file in Index != Previous Commit.
            echo "$file - file deleted, different changes staged for commit"
        else
            # Here file in Index == Previous Commit.
            echo "$file - file deleted"
        fi

    # If file is in current directory only.
    elif test -e $file
    then
        echo "$file - untracked"

    # If file is in index only.
    elif test -e .legit/.index/master/$file
    then
        echo "$file - added to index"

    # If file is in previous commmit only.
    elif test -e .legit/.prev/master/$prevCommit/$file
    then
        echo "$file - deleted"
    fi
done
