#!/bin/dash
# Created by Nikil Singh z5209322

# Check if a .legit directory has been initialised.
if  ! test -d .legit
then
    echo "$0: error: no .legit directory containing legit repository exists"
    exit 1
fi

# Checks if commit log is empty.
if ! test -s .legit/.prev/master/commitLog.txt
then
    echo "legit-log: error: your repository does not have any commits yet"
    exit 1
fi

# Prints out the commit log for that branch.
file=.legit/.prev/master/commitLog.txt
tac $file
