#!/bin/dash
# Created by Nikil Singh z5209322

# Check if there are arguements.
if test $# -eq 0
then
    echo "legit-add: error: internal error Nothing specified, nothing added."
    exit 1
fi

# Check if a .legit directory has been initialised.
if  ! test -d .legit
then
    echo "legit-add: error: no .legit directory containing legit repository exists"
    exit 1
fi

# Check if all arguements are valid files.
for file in $@
do
    if ! test -e $file
    then
        echo "legit-add: error: can not open '$file'"
        exit 1
    fi
done

# Adds the files to the index.
for file in $@
do
    cp $file ".legit/.index/master"
done
