#!/bin/dash
# Created by Nikil Singh z5209322

sh legit-init
#Initialized empty legit repository in .legit
touch a b c d e f g h
sh legit-add a b c d e f
sh legit-commit -m 'first commit'
#Committed as commit 0
echo hello >a
echo hello >b
echo hello >c
sh legit-add a b
echo world >a
rm d
sh legit-rm e
sh legit-add g


# a - file changed, different changes staged for commit
# b - file changed, changes staged for commit
# c - file changed, changes not staged for commit
# d - file deleted
# e - deleted
# f - same as repo
# g - added to index
# h - untracked
# legit-add - untracked
# legit-commit - untracked
# legit-init - untracked
# legit-rm - untracked
# legit-status - untracked
