#!/bin/dash
# Created by Nikil Singh z5209322

sh legit-init
#Initialized empty legit repository in .legit
echo 1 >a
echo 2 >b
echo 3 >c
sh legit-add a b c
sh legit-commit -m "first commit"
#Committed as commit 0
echo 4 >>a
echo 5 >>b
echo 6 >>c
echo 7 >d
echo 8 >e
sh legit-add b c d
echo 9 >b
